### ISSUE TITLE
Time of measure

### ISSUE THREAD

**Issue by aageberg** [swharden/pyTENMA#1]
Hi! This script looks just like what I’m looking for. Is it possible to include a time stamp (real clock) on each measurement?

**Comment by swharden** [comment]
Yeah! Modify this line: https://github.com/swharden/pyTENMA/blob/master/pyTENMA.py#L246

and change it from:
```python
f.write(text)
```
to something like:
```python
timestamp = time.strftime('%Y-%m-%d, %H:%M:%S', time.localtime())
f.write(timestamp +"," + text)
```
