### ISSUE TITLE
"connect" method should be referred from within

### ISSUE THREAD

**Issue by davidbleloch** [swharden/pyTENMA#2]
Method "connect" fails its surrounding try-except as it is referred using the instance name provided in the demo file ("PT").  Should read self.connect()?

**Comment by swharden** [comment]
Hi @davidbleloch, sorry to hear you are having trouble with this script! It was developed for a TENMA 72-7750 and I understand you are using a TENMA 72-10415, so it's possible TENMA has changed its protocol. That said, I'd love to support both. It would be helpful if you could copy/paste the full error message here so I can take a closer look. Thanks!

**Comment by swharden** [comment]
Upon closer inspection, it looks like this line may contain a bug

https://github.com/swharden/pyTENMA/blob/9bf966f44dbf43b00a70230cb1a1b237bd5e35d3/pyTENMA.py#L232

...and replacing `PT.` with `self.` may fix this bug.

If you try this replacement on your end, does the script work?

**Comment by davidbleloch** [comment]
hi @swharden , many thanks for the prompt response.  Yes, changing line 232 as you have suggested allows the script to connect successfully to the equipment and stream DMM readings.  Note : tested using an (unsupported) 72-10415 meter with one additional significant digit which causes the formatting of the returned value is now incorrect.
