### ISSUE TITLE
Incorrect  mode on TENMA 72-10415

### ISSUE THREAD

**Issue by zeleny-ondrej** [swharden/pyTENMA#3]
Hello,

Firstly, thank you for creating this script. It looks like the output format may differ between various models of TENMA multimeter. I tries using this on my 72-10415 which is 22000 count multimeter and it did not work since the actual data are longer.

This is not an issue with the script just a heads up for someone who might wanna use it and is getting incorrect reading. What you wanna do is to play a little bit with the `formalVal` function and correct the format. I highly recommend connecting and the multimeter to a resistor or a dc power supply to work out the correct format in case the original does not work. The modes may also differ in case you multimeter offer multiple measurement options on the same position of the rotary switch (for example i can switch from AC to frequency measurement using another button. This means the data i read contain two mode symbols.

Example:

DC voltage:
[0 0000 0; 000:0]	 0.0000 V

AC voltage (first mode is the same ';', but the 11th value is different):
[0 0000 0; 00060]	 0.0000 V

also manual range in DC voltage mode:

[0 0000 0; 00080]	 0.0000 V

Note: there are no values in these data frames, voltage was measured in this case.

**Comment by swharden** [comment]
> This is not an issue with the script just a heads up for someone who might wanna use it and is getting incorrect reading

Thanks for sharing this information @zeleny-ondrej! This isn't a project I've worked on for a while, but I appreciate you sharing your findings about the [TENMA 72-10415](https://www.amazon.com/Professional-Digital-Multimeter-72-10415-Display/dp/B00EID8TI0) which may help others who search for this topic in the future 👍 🚀
